apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  labels:
    app: app-gui
spec:
  selector:
    matchLabels:
      app: app-gui
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-gui
    spec:
      containers:
        - image: chenghuajie/gui
          imagePullPolicy: Always
          name: gui
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gui-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.133.18.222
  ports:
    - port:  5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: app-gui