apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  labels:
    app: app-sonar
spec:
  selector:
    matchLabels:
      app: app-sonar
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-sonar
    spec:
      containers:
        - image: chenghuajie/sonar
          imagePullPolicy: Always
          name: sonar
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  ports:
    - port:  8000
      protocol: TCP
      targetPort: 9000
  selector:
    app: app-sonar