apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app: app-spark
spec:
  selector:
    matchLabels:
      app: app-spark
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-spark
    spec:
      containers:
        - image: bitnami/spark
          imagePullPolicy: Always
          name: spark
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  ports:
    - port:  8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-spark